import Foundation

/// The two languages Dodoma scores text against.
public enum Language: String, Sendable, CaseIterable {
    case english = "en"
    case arabic = "ar"

    public var displayName: String {
        switch self {
        case .english: return "English"
        case .arabic: return "Arabic"
        }
    }
}

/// How much a piece of text looks like a given language.
///
/// Both components are 0…1. `bigram` is a shape signal (does the letter
/// sequence look like the language?) and `dictCoverage` is a lexical one (are
/// these actual words?). They fail in different directions — a novel name
/// scores well on shape and badly on lexicon, an acronym the reverse — so the
/// decision layer reads the blend.
public struct Score: Equatable, Sendable {
    public let bigram: Double
    public let dictCoverage: Double
    public let combined: Double

    /// Weights of the blend. Shape leads because it degrades gracefully:
    /// dictionary coverage is all-or-nothing per token and a single unlisted
    /// word would otherwise halve the score of a correct sentence.
    public static let bigramWeight = 0.55
    public static let dictWeight = 0.45

    public init(bigram: Double, dictCoverage: Double) {
        self.bigram = bigram
        self.dictCoverage = dictCoverage
        self.combined = Self.bigramWeight * bigram + Self.dictWeight * dictCoverage
    }

    public static let zero = Score(bigram: 0, dictCoverage: 0)
}

/// Offline word list plus letter-bigram model for one language.
///
/// Both resources are generated by `Tools/build-ngrams.py` and committed under
/// `Sources/DodomaCore/Resources`. Loading is lazy (the app starts long before
/// the first keystroke needs scoring) and guarded by a lock because scoring
/// runs on the typing queue while the menu bar may touch the same instance.
public final class LanguageModel: @unchecked Sendable {
    public enum LoadError: Error, CustomStringConvertible {
        case missingResource(String)
        case malformed(String)

        public var description: String {
            switch self {
            case .missingResource(let name):
                return "language resource \(name) is missing from the bundle"
            case .malformed(let name):
                return "language resource \(name) is malformed"
            }
        }
    }

    public let language: Language

    private let bundle: Bundle?
    /// Words this user writes, consulted alongside the shipped list.
    ///
    /// Held weakly by nobody: the pipeline owns one lexicon and hands the same
    /// instance to both models, so a word learned while writing English is not
    /// mistaken for an Arabic one.
    public var lexicon: UserLexicon?

    private let lock = NSLock()
    private var cached: Tables?

    private struct Tables {
        let words: Set<String>
        let bigrams: BigramTable
    }

    /// Pass `bundle` only to read the tables from somewhere other than the
    /// package's own resource bundle; `nil` uses `CoreResources`.
    public init(language: Language, bundle: Bundle? = nil) {
        self.language = language
        self.bundle = bundle
    }

    // MARK: - Shared instances

    private static let sharedLock = NSLock()
    private nonisolated(unsafe) static var sharedModels: [Language: LanguageModel] = [:]

    /// Process-wide instance, so the 800 KB of tables is parsed at most once.
    public static func shared(_ language: Language) -> LanguageModel {
        sharedLock.lock()
        defer { sharedLock.unlock() }
        if let existing = sharedModels[language] { return existing }
        let model = LanguageModel(language: language)
        sharedModels[language] = model
        return model
    }

    /// Forces the tables in, so a caller can surface a missing-resource error
    /// at startup instead of silently scoring everything as zero.
    public func preload() throws {
        _ = try tables()
    }

    // MARK: - Scoring

    /// Mean log-probability of the text's letter pairs, mapped onto 0…1.
    ///
    /// Every token is scored as `^token$`, so word starts and ends count.
    /// Characters outside the language's alphabet do not participate; they end
    /// the current token. Text with no scoreable pair at all scores 0.
    public func bigramScore(_ text: String) -> Double {
        guard let tables = try? tables() else { return 0 }
        let table = tables.bigrams
        let normalized = Self.normalize(text, for: language)

        var total = 0.0
        var pairs = 0
        var previous: Int?

        func closeToken() {
            if let previous {
                total += table.logProb(previous, table.boundaryIndex)
                pairs += 1
            }
            previous = nil
        }

        for character in normalized {
            guard let index = table.index(of: character) else {
                closeToken()
                continue
            }
            total += table.logProb(previous ?? table.boundaryIndex, index)
            pairs += 1
            previous = index
        }
        closeToken()

        guard pairs > 0 else { return 0 }
        return table.calibrate(total / Double(pairs))
    }

    /// Share of the text, weighted by token length, that is in the word list.
    ///
    /// One-letter tokens are dropped entirely (they are punctuation-adjacent
    /// noise and both languages have single letters that are words), two-letter
    /// tokens count half, longer tokens count their letters. Long words
    /// therefore dominate, which is what we want: `hgdml` being unknown is far
    /// more informative than `hc` being unknown.
    public func dictCoverage(_ text: String) -> Double {
        guard let tables = try? tables() else { return 0 }
        var covered = 0.0
        var total = 0.0
        for token in tokens(in: text, alphabet: tables.bigrams) {
            let length = token.count
            guard length > 1 else { continue }
            let weight = length == 2 ? 0.5 : Double(length)
            total += weight
            if isKnown(token, in: tables) { covered += weight }
        }
        guard total > 0 else { return 0 }
        return covered / total
    }

    public func combined(_ text: String) -> Score {
        Score(bigram: bigramScore(text), dictCoverage: dictCoverage(text))
    }

    /// Word-list membership for an already-tokenised word, including the
    /// affix stripping `dictCoverage` applies. Exposed for tests and the CLI.
    public func isKnownWord(_ word: String) -> Bool {
        guard let tables = try? tables() else { return false }
        return isKnown(Self.normalize(word, for: language), in: tables)
    }

    private func tokens(in text: String, alphabet: BigramTable) -> [String] {
        var out: [String] = []
        var current = ""
        for character in Self.normalize(text, for: language) {
            if alphabet.index(of: character) != nil {
                current.append(character)
            } else if !current.isEmpty {
                out.append(current)
                current = ""
            }
        }
        if !current.isEmpty { out.append(current) }
        return out
    }

    private func isKnown(_ token: String, in tables: Tables) -> Bool {
        for candidate in Self.lookupForms(of: token, language: language) {
            if tables.words.contains(candidate) { return true }
            // The user's own vocabulary counts as much as the shipped list.
            // Checked on the same affix-stripped forms, so a learned stem is
            // still recognised with a clitic or a plural attached.
            if lexicon?.contains(candidate, language: language) == true { return true }
        }
        return false
    }

    /// Tokens of this text, as `dictCoverage` sees them. The learning path uses
    /// it so what gets counted is exactly what would later be looked up.
    public func vocabulary(in text: String) -> [String] {
        guard let tables = try? tables() else { return [] }
        return tokens(in: text, alphabet: tables.bigrams)
    }

    // MARK: - Morphology

    /// English inflections that the frequency list often lacks for rarer stems.
    static let englishSuffixes = ["'s", "s", "es", "ed", "ing"]
    /// Arabic proclitics, longest first so `وال` wins over `و`.
    static let arabicPrefixes = ["وال", "بال", "فال", "كال", "لل", "ال", "و", "ف", "ب", "ل"]
    /// Attached pronouns.
    static let arabicSuffixes = ["ها", "هم", "كم", "كن", "نا", "ه", "ك", "ي"]

    /// The token plus every affix-stripped form worth looking up. A stripped
    /// form shorter than two letters is dropped: `ال` alone would match half
    /// the language.
    static func lookupForms(of token: String, language: Language) -> [String] {
        var forms = [token]
        switch language {
        case .english:
            for suffix in englishSuffixes where token.hasSuffix(suffix) {
                let stem = String(token.dropLast(suffix.count))
                if stem.count >= 2 { forms.append(stem) }
            }
        case .arabic:
            let prefixed = [token] + arabicPrefixes.compactMap { prefix -> String? in
                guard token.hasPrefix(prefix) else { return nil }
                let stem = String(token.dropFirst(prefix.count))
                return stem.count >= 2 ? stem : nil
            }
            for stem in prefixed {
                if stem != token { forms.append(stem) }
                for suffix in arabicSuffixes where stem.hasSuffix(suffix) {
                    let core = String(stem.dropLast(suffix.count))
                    if core.count >= 2 { forms.append(core) }
                }
            }
        }
        return forms
    }

    /// Folds the orthographic variation that keyboards and writers treat as
    /// interchangeable, exactly as `Tools/build-ngrams.py` does when it builds
    /// the tables. Anything else would look words up in a form the list does
    /// not contain.
    public static func normalize(_ text: String, for language: Language) -> String {
        switch language {
        case .english:
            return text.lowercased()
        case .arabic:
            var out = String()
            out.reserveCapacity(text.count)
            for scalar in text.unicodeScalars {
                if arabicStrippedScalars.contains(scalar) { continue }
                if let folded = arabicFolds[scalar] {
                    out.unicodeScalars.append(folded)
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
            return out
        }
    }

    /// Tatweel, the harakat block and the superscript alef: decoration that
    /// carries no lexical weight and is usually not typed at all.
    private static let arabicStrippedScalars: Set<Unicode.Scalar> = {
        var set: Set<Unicode.Scalar> = ["\u{0640}", "\u{0670}"]
        for value in 0x064B...0x0652 {
            set.insert(Unicode.Scalar(value)!)
        }
        return set
    }()

    private static let arabicFolds: [Unicode.Scalar: Unicode.Scalar] = [
        "\u{0623}": "\u{0627}",  // أ -> ا
        "\u{0625}": "\u{0627}",  // إ -> ا
        "\u{0622}": "\u{0627}",  // آ -> ا
        "\u{0671}": "\u{0627}",  // ٱ -> ا
        "\u{0649}": "\u{064A}",  // ى -> ي
        "\u{0629}": "\u{0647}",  // ة -> ه
    ]

    // MARK: - Loading

    private func tables() throws -> Tables {
        lock.lock()
        defer { lock.unlock() }
        if let cached { return cached }
        let loaded = Tables(
            words: try loadWords(),
            bigrams: try loadBigrams())
        cached = loaded
        return loaded
    }

    private func resourceURL(_ name: String) throws -> URL {
        if let bundle {
            guard
                let url = bundle.url(forResource: name, withExtension: nil, subdirectory: "Resources")
                    ?? bundle.url(forResource: name, withExtension: nil)
            else { throw LoadError.missingResource(name) }
            return url
        }
        guard let url = CoreResources.url(forResource: name) else {
            throw LoadError.missingResource(name)
        }
        return url
    }

    private func loadWords() throws -> Set<String> {
        let name = "\(language.rawValue).words"
        let text = try String(contentsOf: try resourceURL(name), encoding: .utf8)
        var words = Set<String>()
        words.reserveCapacity(40_000)
        for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
            words.insert(String(line))
        }
        guard !words.isEmpty else { throw LoadError.malformed(name) }
        return words
    }

    private func loadBigrams() throws -> BigramTable {
        let name = "\(language.rawValue).bigrams.json"
        let data = try Data(contentsOf: try resourceURL(name))
        let payload: BigramTable.Payload
        do {
            payload = try JSONDecoder().decode(BigramTable.Payload.self, from: data)
        } catch {
            throw LoadError.malformed(name)
        }
        guard let table = BigramTable(payload) else { throw LoadError.malformed(name) }
        return table
    }
}

/// Row-major letter-bigram log-probability table with its 0…1 calibration.
///
/// Index `alphabet.count` is the boundary symbol, standing in for both `^` and
/// `$`, so `^cat$` is four transitions.
struct BigramTable {
    struct Payload: Decodable {
        let alphabet: String
        let boundary: Bool
        let logProb: [[Double]]
        let floor: Double
        let ceiling: Double
    }

    let boundaryIndex: Int
    let floor: Double
    let ceiling: Double

    private let rows: [[Double]]
    private let indices: [Character: Int]

    init?(_ payload: Payload) {
        let size = payload.alphabet.count + 1
        guard payload.boundary,
              payload.logProb.count == size,
              payload.logProb.allSatisfy({ $0.count == size }),
              payload.ceiling > payload.floor
        else { return nil }

        var indices: [Character: Int] = [:]
        for (position, character) in payload.alphabet.enumerated() {
            indices[character] = position
        }
        guard indices.count == payload.alphabet.count else { return nil }

        self.rows = payload.logProb
        self.indices = indices
        self.boundaryIndex = size - 1
        self.floor = payload.floor
        self.ceiling = payload.ceiling
    }

    func index(of character: Character) -> Int? { indices[character] }

    func logProb(_ from: Int, _ to: Int) -> Double { rows[from][to] }

    func calibrate(_ meanLogProb: Double) -> Double {
        min(1, max(0, (meanLogProb - floor) / (ceiling - floor)))
    }
}
